// 
// Copyright(c) 1993-1996 Tony Kirke
// author="Tony Kirke" *
/* Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  This software is provided "as is" 
 * without express or implied warranty.
*/
#ifndef IIR1STHC
#define IIR1STHC
namespace SPUC {
/*! \brief  Template Class for 1st Order high pass iir filter
    \ingroup iir
*/
//
//!  Template for 1st Order IIR filter<p>
//!   The filter is assumed the first order high pass digital filter 
//!   generated by the bilinear transform of a first order analog 
//!   filter<p>.
//!   \f$ G(z) =  \frac{1+z^{-1}}{1-a*z^{-1}} \f$ where a is real and |a| < 1
//!   Note: Not normalized
template <class Numeric> class iir_hpc
{
    protected:   
    	double gain;                    
    	double coeff;                    
    	Numeric out;
        Numeric previous_out;
		Numeric previous_in;
        
    public:
        iir_hpc(double A=0) {
		  set_coeff(A);
		  previous_in = previous_out = out = 0 ; 
		}
		void set_coeff(double A) { 
		  coeff=A;
		  gain=2.0/(1+coeff);
		}
		//! Constructor reading coefficient from a file.
		iir_hpc(const char* file)
		  {
			FILE *iirf = fopen(file,"r"); 
			fscanf(iirf,"%lf",&coeff);
			fclose(iirf);
			previous_in = previous_out = out = 0;
			set_coeff(coeff);
		  }             
		//! Print out coefficients
		void print() {printf("IIR Coefficient gain = %lf\n",gain);}
		//! Input new sample and calculate output
		Numeric clock(Numeric input) {
		  //! Shift previous outputs and calculate new output */
		  out += (input-coeff*previous_in);
		  previous_in = input;
		  return(gain*out);
		}
		//! Reset
		void reset() {
		  previous_in = previous_out = out = 0;
		}
};       
} // namespace SPUC
#endif
